name: prueba_cootrafa_frontend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  go_router: ^14.8.1
  fpdart: ^1.1.1
  flutter_bloc: ^8.1.3
  logger: ^2.5.0
  get_it: ^8.0.3
  dropdown_button2: ^2.3.9
  syncfusion_flutter_core: ^29.1.33
  syncfusion_flutter_datagrid: ^29.1.33
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
